spring:
  application:
    name: status-server
  datasource:
    url: jdbc:postgresql://localhost:5432/statusdb
    username: statususer
    password: statuspass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
